### ISSUE TITLE
[feat] 할인가, 할인기간 등록

### ISSUE THREAD

**Issue by yeseul0809** [yeseul0809/LeafyLink#128]
## 어떤 기능인가요?
> 기존 상품등록에서 할인가, 할인기간 등록기능 추가

## 작업 상세 내용
- [x] 할인가 등록
- [x] 할인기간 등록 (달력으로 할건지 / 기간입력으로 할건지)

## 예상완료일
- 9/19

## 참고할만한 자료(선택)

**Comment by sonsy723** [comment]
화이팅~
